server:
  port: 1234
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true
spring:
  config:
    import: optional:file:.env.dev[.properties]
  application:
    name: hello-service
  datasource:
    username: ${DB.USERNAME:root}
    password: ${DB.PASSWORD:123456}
    url: jdbc:${DB.TYPE:mysql}://${DB.IP:localhost}:${DB.PORT:3306}/${DB.DATABASE:redbook}?useSSL=false&serverTimezone=UTC&charset=utf8mb4
  data:
    redis:
      host: ${REDIS.HOST:localhost}
      port: ${REDIS.PORT:6379}
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000
logging:
  level:
    org.springframework.security: trace