server:
  port: 9000
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: uaa-service
  datasource:
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    url: jdbc:${DB.TYPE}://${DB.IP}:${DB.PORT}/${DB.DATABASE}?useSSL=false&serverTimezone=UTC&charset=utf8mb4
  data:
    redis:
      host: ${REDIS.HOST}
      port: ${REDIS.PORT}
logging:
  level:
    org.springframework.security: trace