server:
  port: 10000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: hello
          uri: lb://hello-service
          predicates:
            - Path=/api/hello/**
          filters:
            - StripPrefix=1
        - id: uaa
          uri: lb://uaa-service
          predicates:
            - Path=/api/oauth2/**
          filters:
            - StripPrefix=1